### ISSUE TITLE
Fix setup.py to work with setuptools 41.4.0 and later

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_fs#20]
I haven't tested it, but looking at the `setup.py` file in this repo concerns me, if here couldn't happen the same problem with `setuptools>=41.4.0` as we encountered in the `kaitai_struct_python_runtime` repo (https://github.com/kaitai-io/kaitai_struct_python_runtime/pull/46).

In this comment https://github.com/kaitai-io/kaitai_struct_python_runtime/issues/43#issuecomment-600618779 in the issue reporting the problem, @dgelessus wrote this:

> This error is caused by setup.py files trying to read setup.cfg manually, which is not officially supported (see pypa/setuptools#1869). You're supposed to just call `setup()` without arguments and let setuptools find and read the setup.cfg file itself.

If that was the case, I think the same can happen also in this repo. Here's the `setup.py` here:

https://github.com/kaitai-io/kaitai_fs/blob/0c4a7731d45578b4a18dbcb683e6bbd255e2e842/setup.py#L7-L11

I don't have any deep experience with setuptools, setup.py and this kind of stuff, but this seems to me a lot like _setup.py files trying to read setup.cfg manually_.

@dgelessus, could you please look at it and possibly fix it?

**Comment by dgelessus** [comment]
Just tested - `python3 -m pip install ./kaitai_fs` actually works without issues with `pip==20.1.1` and `setuptools==47.3.1` (which are the latest versions currently).

The error that we had with kaitai_struct_python_runtime only happens when you read setup.cfg manually *and* the setup.cfg has a `python_requires` setting in the `[options]` section. kaitai_fs's setup.cfg doesn't use `python_requires`, so the error doesn't occur here.

You are right though that the setup.py here is manually reading/parsing setup.cfg, which is not supported (even though it doesn't give any errors here), so we should fix that. I'll make a PR.

**Comment by generalmimon** [comment]
@dgelessus Thanks for your review and the clarification, at least I'm a little wiser :slightly_smiling_face:
